name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/CI-CD/.github/workflows/build-dotnet.yml@main
    secrets: inherit
    with:
      project_path: 'Application.csproj'
      test_path: 'Application.Tests/Application.Tests.csproj'
      dependencies: 'Platform-System/Domain,Platform-System/BuildingBlocks'



